iscsi: workaround for hba_info going missing in Linux 4.7
Starting with 4.7 kernels we occasionally see the following backtraces
from the backstore resources:

Traceback (most recent call last): ]
  File "/usr/lib/ocf/resource.d/rtslib/iscsi", line 27, in <module> ]
    ISCSITargetAgent.main() ]
  File "build/bdist.linux-x86_64/egg/ocf/ra.py", line 464, in main ]
  File "build/bdist.linux-x86_64/egg/ocf/ra.py", line 525, in execute ]
  File "build/bdist.linux-x86_64/egg/ocf_rtslib/iscsi.py", line 349, in monitor ]
  File "build/bdist.linux-x86_64/egg/ocf/util.py", line 38, in __get__ ]
  File "build/bdist.linux-x86_64/egg/ocf_rtslib/iscsi.py", line 152, in storage_objects ]
  File "/usr/lib/python2.7/dist-packages/rtslib/tcm.py", line 81, in _get_plugin ]
    return self._parse_info("plugin") ]
  File "/usr/lib/python2.7/dist-packages/rtslib/tcm.py", line 71, in _parse_info ]
    info = fread("%s/hba_info" % self.path) ]
  File "/usr/lib/python2.7/dist-packages/rtslib/utils.py", line 100, in fread ]
    file_fd = open(path, 'r') ]
IOError: [Errno 2] No such file or directory: '/sys/kernel/config/target/core/iblock_11/hba_info' ]

Because this is so intermittent, simply work around it by retrying a few
times until it works.

This is the same fix as for the backstore OCF script.